MASTER_NODE_NAME = 'ftonitaS'
MASTER_NODE_IP = '192.168.42.110'
MASTER_SCRIPT = "scripts/centos-gitlab.sh"

CPU = 1
MEM = 1024
BOX = "../centos_image"
BOX_AUTO_UPDATE = false

$DISABLE_FIREWALL_SCRIPT = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL

Vagrant.configure("2") do |config|
	config.vm.box = BOX
	config.vm.box_check_update = BOX_AUTO_UPDATE
	config.vbguest.installer_options = { allow_kernel_upgrade: true }
	config.vm.provision "shell", inline: $DISABLE_FIREWALL_SCRIPT 

	config.vm.provider "virtualbox" do |v|
		v.memory = MEM
		v.cpus = CPU
	end

	config.vm.define MASTER_NODE_NAME do |master|
		master.vm.hostname = MASTER_NODE_NAME
		master.vm.network :private_network, ip: MASTER_NODE_IP
		master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		master.vm.provision "shell", privileged: true, path: MASTER_SCRIPT, args: [MASTER_NODE_IP]
		master.vm.provider "virtualbox" do |v|
			v.name = MASTER_NODE_NAME
		end
	end
end
